import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Header from "../sharedComponents/Header";

const HomepageLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>NetErnels Web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box as="main">{children}</Box>
        </>
    );
};

export default HomepageLayout;
