import Head from "next/head";
import { Inter } from "@next/font/google";
import PrimaryContainer from "@/components/widgets/PrimaryContainer";
import { Box, Text } from "@chakra-ui/react";
import useColors from "@/hooks/useColors";
import HeroSection from "@/components/ui/index/HeroSection";
import KernelsDeveloped from "@/components/ui/index/KernelsDeveloped";
import { useState } from "react";
import CardsContainer from "@/components/ui/index/CardsContainer";

export default function Home() {
    const [devices, setDevices] = useState([...Array(12)]);
    return (
        <>
            <Head>
                <title>NetErnels Web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box as="main">
                <HeroSection />
                <KernelsDeveloped />
                <CardsContainer devices={devices} />
            </Box>
        </>
    );
}
